// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBanco.Api.Data;

#nullable disable

namespace ProjetoBanco.Api.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    partial class BancoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.Api.Models.Agencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AgenciaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Contratacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MotivoReprovacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PrazoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("ValorSolicitado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Contratacoes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoProdutoBanco")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProdutoBanco").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Models.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("Score")
                        .HasColumnType("NUMBER(10)");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<decimal>("FaturamentoMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Score")
                        .HasColumnType("NUMBER(10)");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.ToTable("Clientes", t =>
                        {
                            t.Property("Score")
                                .HasColumnName("PessoaJuridica_Score");
                        });

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Emprestimo", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Models.Produto");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = 1,
                            Nome = "Empréstimo Pessoal",
                            Tipo = 1,
                            PrazoMaximoMeses = 48,
                            TaxaJurosMensal = 0.035m,
                            ValorMaximo = 50000m,
                            ValorMinimo = 500m
                        });
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Models.Produto");

                    b.Property<decimal>("FaturamentoMinimoMensal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("MdrCreditoAVista")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("MdrCreditoParcelado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("MdrDebito")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Ativo = 1,
                            Nome = "Máquina de Cartão",
                            Tipo = 2,
                            FaturamentoMinimoMensal = 3000m,
                            MdrCreditoAVista = 0.0349m,
                            MdrCreditoParcelado = 0.0499m,
                            MdrDebito = 0.0199m
                        });
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.ReceberSalario", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Models.Produto");

                    b.Property<int>("ExigeConvenioEmpregador")
                        .HasColumnType("NUMBER(1)");

                    b.HasDiscriminator().HasValue("RECEBER_SALARIO");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            Ativo = 1,
                            Nome = "Receber Salário",
                            Tipo = 3,
                            ExigeConvenioEmpregador = 1
                        });
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Cliente", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Models.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Contratacao", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Models.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoBanco.Api.Models.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Models.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
